- name: Create & configure Azure blockchain infrastructure
  hosts: localhost
  connection: local

  vars_prompt:
  - name: "ethereumAccountPsswd"
    prompt: "Enter Ethereum Account Password"
    private: yes
  - name: "ethereumAccountPassphrase"
    prompt: "Enter Ethereum Account Passphrase"
    private: yes

  tasks:
    - include_tasks: infra.yml
      vars:
        location: '{{ loc.dc }}'
        fileLocation: https://raw.githubusercontent.com/luberan/blockchain-ansible-template/master/ansible-template-2dc/
        adminSSHKey: "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAnkcRVB1hFReDvvW9BeO3RHkmBdhTe1e4Mo7Mnq/s1WlM4SPz5gSnp++PfJzdNdpgSHayxc5mLxGHazcHlctr+n0myv32pQEAiWD6nRGy9D+lOy7EfH7Q8SHDRLSht0S3uUSshH+EgJomDsLVAfIr5biqJkjc+M6OPHXNd/U0kxDVldVnZN06n36OxBkK6uO0h2Lw+x1cw57AjwsRUYWD0KA85+f9gkAxFQVbsperJS7WztzUYjA7pjqivwqyMO84W8+QBowrxcUcDRhTIOYMVFusTUcebKJ76XNwkhMuwv56GblnUC6P4moAv2B+Qb9DftNmf93kdEeFnyFxmdXgMw== rsa-key-20180207"
        rgname: '{{ namePrefix + "-" + loc.dc }}'
        namePrefix: ethtest
        adminUsername: gethadmin
        numConsortiumMembers: 2
        numMiningNodesPerMember: 1
        txNodeVMSize: Standard_A1_v2
        numTXNodes: 1
        mnNodeVMSize: Standard_A1_v2
        availabilitySetName: '{{ namePrefix + "-avset" }}'
        httpPort: 80
        adminSitePort: 3000
        sshPort: 22
        sshNATFrontEndStartingPort: 3000
        gethRPCPort: 8545
        loadBalancerInboundNatRuleNamePrefix: ssh-vm
        numMNNodes: '{{ numConsortiumMembers * numMiningNodesPerMember }}'
        loadBalancerName: '{{ namePrefix + "-lb" }}'
        loadBalancerBackendAddressPoolName: LoadBalancerBackend1
        mnVMNamePrefix: '{{ namePrefix + "-mn" }}'
        mnNICPrefix: '{{ namePrefix + "-nic-mn" }}'
        txVMNamePrefix: '{{ namePrefix + "-tx" }}'
        txSubnetName: '{{ namePrefix + "-tx-subnet" }}'
        txSubnetPrefix: '{{ loc.txSubnet }}'
        txNIPrefix: '{{ namePrefix + "-nic-tx" }}'
        virtualNetworkName: '{{ namePrefix + "-vnet" }}'
        txNsgName: '{{ namePrefix + "-txnsg" }}'
        mnNsgName: '{{ namePrefix + "-mnnsg" }}'
        addressPrefix: '{{ loc.netAddressPrefix }}'
        netNum: '{{ loc.net }}'
        numSubnets: '{{ numConsortiumMembers }}'
        ubuntuImage: {
          "publisher": "Canonical",
          "offer": "UbuntuServer",
          "sku": "16.04-LTS",
          "version": "latest"
        }
        ethereumNetworkID: 72
        gethIPCPort: 30303
      with_items:
        - { dc: 'westeurope', netAddressPrefix: '10.0.0.0/16', txSubnet: '10.0.0.0/24', net: 0 }
        - { dc: 'eastus', netAddressPrefix: '10.1.0.0/16', txSubnet: '10.1.0.0/24', net: 1 }
      loop_control:
        loop_var: loc
