- name: Create & configure Azure blockchain infrastructure
  hosts: localhost
  connection: local

  vars_prompt:
  - name: "ethereumAccountPsswd"
    prompt: "Enter Ethereum Account Password"
    private: yes
  - name: "ethereumAccountPassphrase"
    prompt: "Enter Ethereum Account Passphrase"
    private: yes

  tasks:
  - include: dc1.yml
  - include: dc2.yml