- name: Create & configure Azure blockchain infrastructure
  hosts: localhost
  connection: local

  vars_prompt:
  - name: "ethereumAccountPsswd"
    prompt: "Enter Ethereum Account Password"
    private: yes
  - name: "ethereumAccountPassphrase"
    prompt: "Enter Ethereum Account Passphrase"
    private: yes

  tasks:
    - include_tasks: infra.yml
      vars:
        location: '{{ loc }}'
        fileLocation: https://raw.githubusercontent.com/luberan/blockchain-ansible-template/master/ansible-template/
        subscription_id: 315e66d2-b933-43ae-9af1-e401260cff54
        adminSSHKey: "ssh-rsa
AAAAB3NzaC1yc2EAAAABJQAAAQEAjzz6DGtXvAkWhgmqKpUx4kTyuQCmjStL1CB/
L5ZFaLfEBUA52tY8jzWih8AojoGJFiQv+2mPyIKi1k7zKpsbWDtxbAkAeCKhb+Gv
on3ITNSSV17900qBySgrNpf35s/yKH7lVuMyVAU7GSrBMxEZwvG8L6w3uoacsATp
AxMALyWBEzmySIm9iTM/6ks3Q7Ru4HWXLrfupVHfkZqwqhK1yywbZ+EcDTw4AO0N
GC6POdt4LafB6ujW3OeWgaAeIaPPnfr32J8mudhDzZO7xuSgAzQYSkvHOUGqopfp
77MZ1MuBLfqP6qHDuRDQ1Du9k9Jw/BeYQ5+XB+RwWZyPM7Q1UQ=="
        rgname: '{{ namePrefix + "-" + loc }}'
        namePrefix: eth
        companyName: trask
        namingInfix: '{{ namePrefix + companyName }}'
        adminUsername: gethadmin
        numConsortiumMembers: 2
        numMiningNodesPerMember: 1
        txNodeVMSize: Standard_A1_v2
        numTXNodes: 1
        mnNodeVMSize: Standard_A1_v2
        availabilitySetName: AvSet
        httpPort: 80
        adminSitePort: 3000
        sshPort: 22
        sshNATFrontEndStartingPort: 3000
        gethRPCPort: 8545
        loadBalancerInboundNatRuleNamePrefix: ssh-vm
        numMNNodes: '{{ numConsortiumMembers * numMiningNodesPerMember }}'
        loadBalancerName: '{{ namingInfix + "-lb" }}'
        loadBalancerBackendAddressPoolName: LoadBalancerBackend1
        mnVMNamePrefix: '{{ namingInfix + "-mn" }}'
        mnNICPrefix: nic-mn
        txVMNamePrefix: '{{ namingInfix + "-tx" }}'
        txSubnetName: '{{ namingInfix + "tx" }}'
        txSubnetPrefix: 10.0.0.0/24
        txNIPrefix: nic-tx
        virtualNetworkName: '{{ namingInfix + "vnet" }}'
        txNsgName: '{{ namingInfix + "TXNsg" }}'
        mnNsgName: '{{ namingInfix + "MNNsg" }}'
        addressPrefix: 10.0.0.0/20
        vnetID: '{{ "/subscriptions/" + subscription_id + "/resourceGroup/" + rg + "/providers/Microsoft.Network/virtualNetworks" }}'
        numSubnets: '{{ numConsortiumMembers }}'
        ubuntuImage: {
          "publisher": "Canonical",
          "offer": "UbuntuServer",
          "sku": "16.04-LTS",
          "version": "latest"
        }
      with_items:
        - westeurope
        - eastus
      loop_control:
        loop_var: loc
